### ISSUE TITLE
Execution via helmfile - problem with kube-context flag

### ISSUE THREAD

**Issue by messiahUA** [mumoshu/helm-x#21]
Trying to execute helmfile as per https://github.com/mumoshu/helm-x/tree/master/examples/helmfile:

> helmfile --helm-binary ~/.helm/plugins/helm-x/bin/helm-x --log-level debug apply

but helm-x fails and exits as there is a problem with kube-context flag:

`F0711 07:43:52.685204    5736 main.go:51] unknown flag: --kube-context`

**Comment by mheers** [comment]
You can update your helmfile like this:
```
helmDefaults:
  timeout: 600
  # kubeContext: {{ .Environment.Values.kubeContext }}
  args:
    - "----kubecontext {{ .Environment.Values.kubeContext }}"
```

**Comment by messiahUA** [comment]
Works with the notion that I had to add:
```
environments:
  default:
    values:
      - kubeContext: kubernetes
```
